postgres:
  image: timescale/timescaledb-postgis:latest-pg11
  environment:
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  ports:
    - 5432:5432
  volumes:
    - ./data/postgresql:/var/lib/postgresql/data
